### ISSUE TITLE
我想定制一个关于steam的规则不知道是否可以

### ISSUE THREAD

**Issue by dimogu** [Z-Siqi/Clash-for-Windows_Rule#1]
想要将机场的一些节点放在一起，然后选中的这些节点每间隔2分钟更换一次，或者一个节点每连接steam10次后就更换下一个节点

**Comment by Z-Siqi** [comment]
可以试试[负载均衡](https://github.com/Z-Siqi/Clash-for-Windows_Rule/blob/main/template/README.md#%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1%E7%9A%84%E5%9F%BA%E6%9C%AC%E6%A0%BC%E5%BC%8F)
````
  # load-balance: The request of the same eTLD+1 will be dial to the same proxy.
  - name: "load-balance"
    type: load-balance
    proxies:
      - ss1
      - ss2
      - vmess1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
````
